### ISSUE TITLE
Install on x86 systems

### ISSUE THREAD

**Issue by rafaelsilverioit** [F123/F123Light#1]
Is it possible to install F123Light on x86 systems? Is it easy?

**Comment by fbotelho** [comment]
It will be fairly soon. For more details, please join our list for 
experienced users by sending a blank email to:

f123e+subscribe@groups.io


Thanks,


Fernando

**Comment by rafaelsilverioit** [comment]
Ty @fbotelho for the feedback! I have a been asked to join a project in which I'm being asked to create an installer for x86 systems (due June 26). Do you think I'll be able to achieve this by myself, given that I don't have any knowledge about F123Light yet?

I've subscribed.

Thanks, Rafael

**Comment by fbotelho** [comment]
Yes, Rafael, write to me directly and I will put you in touch with 
people that can help. My direct email is fernando@f123.org


Fernando

**Comment by rafaelsilverioit** [comment]
Ty Fernando, I've sent an email to your mailbox.
Rafael
